CREATE TABLE IF NOT EXISTS books (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author VARCHAR (40),
    book_title VARCHAR (60),
    price_for_one int4,
    the_year_of_publishing int4
    );